// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListProjectsHandlerFunc turns a function with the right signature into a list projects handler
type ListProjectsHandlerFunc func(ListProjectsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListProjectsHandlerFunc) Handle(params ListProjectsParams) middleware.Responder {
	return fn(params)
}

// ListProjectsHandler interface for that can handle valid list projects params
type ListProjectsHandler interface {
	Handle(ListProjectsParams) middleware.Responder
}

// NewListProjects creates a new http.Handler for the list projects operation
func NewListProjects(ctx *middleware.Context, handler ListProjectsHandler) *ListProjects {
	return &ListProjects{Context: ctx, Handler: handler}
}

/*ListProjects swagger:route GET /projects project listProjects

List the projects

Get all projects list.


*/
type ListProjects struct {
	Context *middleware.Context
	Handler ListProjectsHandler
}

func (o *ListProjects) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListProjectsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
