package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"

	"github.com/go-openapi/runtime"

	"api/models"
)

/*ReadProjectOK Project response

swagger:response readProjectOK
*/
type ReadProjectOK struct {
	/*
	  Required: true
	*/
	XErrorCode string `json:"X-Error-Code"`

	// In: body
	Payload *models.Project `json:"body,omitempty"`
}

// NewReadProjectOK creates ReadProjectOK with default headers values
func NewReadProjectOK() *ReadProjectOK {
	return &ReadProjectOK{}
}

// WithXErrorCode adds the xErrorCode to the read project o k response
func (o *ReadProjectOK) WithXErrorCode(xErrorCode string) *ReadProjectOK {
	o.XErrorCode = xErrorCode
	return o
}

// SetXErrorCode sets the xErrorCode to the read project o k response
func (o *ReadProjectOK) SetXErrorCode(xErrorCode string) {
	o.XErrorCode = xErrorCode
}

// WithPayload adds the payload to the read project o k response
func (o *ReadProjectOK) WithPayload(payload *models.Project) *ReadProjectOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the read project o k response
func (o *ReadProjectOK) SetPayload(payload *models.Project) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReadProjectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Error-Code
	rw.Header().Add("X-Error-Code", fmt.Sprintf("%v", o.XErrorCode))

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ReadProjectNotFound Project response

swagger:response readProjectNotFound
*/
type ReadProjectNotFound struct {
	/*
	  Required: true
	*/
	XErrorCode string `json:"X-Error-Code"`

	// In: body
	Payload *models.Project `json:"body,omitempty"`
}

// NewReadProjectNotFound creates ReadProjectNotFound with default headers values
func NewReadProjectNotFound() *ReadProjectNotFound {
	return &ReadProjectNotFound{}
}

// WithXErrorCode adds the xErrorCode to the read project not found response
func (o *ReadProjectNotFound) WithXErrorCode(xErrorCode string) *ReadProjectNotFound {
	o.XErrorCode = xErrorCode
	return o
}

// SetXErrorCode sets the xErrorCode to the read project not found response
func (o *ReadProjectNotFound) SetXErrorCode(xErrorCode string) {
	o.XErrorCode = xErrorCode
}

// WithPayload adds the payload to the read project not found response
func (o *ReadProjectNotFound) WithPayload(payload *models.Project) *ReadProjectNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the read project not found response
func (o *ReadProjectNotFound) SetPayload(payload *models.Project) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReadProjectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Error-Code
	rw.Header().Add("X-Error-Code", fmt.Sprintf("%v", o.XErrorCode))

	rw.WriteHeader(404)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ReadProjectInternalServerError Error response

swagger:response readProjectInternalServerError
*/
type ReadProjectInternalServerError struct {
	/*
	  Required: true
	*/
	XErrorCode string `json:"X-Error-Code"`

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewReadProjectInternalServerError creates ReadProjectInternalServerError with default headers values
func NewReadProjectInternalServerError() *ReadProjectInternalServerError {
	return &ReadProjectInternalServerError{}
}

// WithXErrorCode adds the xErrorCode to the read project internal server error response
func (o *ReadProjectInternalServerError) WithXErrorCode(xErrorCode string) *ReadProjectInternalServerError {
	o.XErrorCode = xErrorCode
	return o
}

// SetXErrorCode sets the xErrorCode to the read project internal server error response
func (o *ReadProjectInternalServerError) SetXErrorCode(xErrorCode string) {
	o.XErrorCode = xErrorCode
}

// WithPayload adds the payload to the read project internal server error response
func (o *ReadProjectInternalServerError) WithPayload(payload *models.Error) *ReadProjectInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the read project internal server error response
func (o *ReadProjectInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReadProjectInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Error-Code
	rw.Header().Add("X-Error-Code", fmt.Sprintf("%v", o.XErrorCode))

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
