// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "api/models"
)

// UpdateProjectOKCode is the HTTP code returned for type UpdateProjectOK
const UpdateProjectOKCode int = 200

/*UpdateProjectOK Project response

swagger:response updateProjectOK
*/
type UpdateProjectOK struct {
	/*

	 */
	XErrorCode string `json:"X-Error-Code"`

	/*
	  In: Body
	*/
	Payload *models.Project `json:"body,omitempty"`
}

// NewUpdateProjectOK creates UpdateProjectOK with default headers values
func NewUpdateProjectOK() *UpdateProjectOK {

	return &UpdateProjectOK{}
}

// WithXErrorCode adds the xErrorCode to the update project o k response
func (o *UpdateProjectOK) WithXErrorCode(xErrorCode string) *UpdateProjectOK {
	o.XErrorCode = xErrorCode
	return o
}

// SetXErrorCode sets the xErrorCode to the update project o k response
func (o *UpdateProjectOK) SetXErrorCode(xErrorCode string) {
	o.XErrorCode = xErrorCode
}

// WithPayload adds the payload to the update project o k response
func (o *UpdateProjectOK) WithPayload(payload *models.Project) *UpdateProjectOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update project o k response
func (o *UpdateProjectOK) SetPayload(payload *models.Project) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateProjectOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Error-Code

	xErrorCode := o.XErrorCode
	if xErrorCode != "" {
		rw.Header().Set("X-Error-Code", xErrorCode)
	}

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateProjectNotFoundCode is the HTTP code returned for type UpdateProjectNotFound
const UpdateProjectNotFoundCode int = 404

/*UpdateProjectNotFound Project response

swagger:response updateProjectNotFound
*/
type UpdateProjectNotFound struct {
	/*

	 */
	XErrorCode string `json:"X-Error-Code"`

	/*
	  In: Body
	*/
	Payload *models.Project `json:"body,omitempty"`
}

// NewUpdateProjectNotFound creates UpdateProjectNotFound with default headers values
func NewUpdateProjectNotFound() *UpdateProjectNotFound {

	return &UpdateProjectNotFound{}
}

// WithXErrorCode adds the xErrorCode to the update project not found response
func (o *UpdateProjectNotFound) WithXErrorCode(xErrorCode string) *UpdateProjectNotFound {
	o.XErrorCode = xErrorCode
	return o
}

// SetXErrorCode sets the xErrorCode to the update project not found response
func (o *UpdateProjectNotFound) SetXErrorCode(xErrorCode string) {
	o.XErrorCode = xErrorCode
}

// WithPayload adds the payload to the update project not found response
func (o *UpdateProjectNotFound) WithPayload(payload *models.Project) *UpdateProjectNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update project not found response
func (o *UpdateProjectNotFound) SetPayload(payload *models.Project) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateProjectNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Error-Code

	xErrorCode := o.XErrorCode
	if xErrorCode != "" {
		rw.Header().Set("X-Error-Code", xErrorCode)
	}

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateProjectInternalServerErrorCode is the HTTP code returned for type UpdateProjectInternalServerError
const UpdateProjectInternalServerErrorCode int = 500

/*UpdateProjectInternalServerError Error response

swagger:response updateProjectInternalServerError
*/
type UpdateProjectInternalServerError struct {
	/*

	 */
	XErrorCode string `json:"X-Error-Code"`

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateProjectInternalServerError creates UpdateProjectInternalServerError with default headers values
func NewUpdateProjectInternalServerError() *UpdateProjectInternalServerError {

	return &UpdateProjectInternalServerError{}
}

// WithXErrorCode adds the xErrorCode to the update project internal server error response
func (o *UpdateProjectInternalServerError) WithXErrorCode(xErrorCode string) *UpdateProjectInternalServerError {
	o.XErrorCode = xErrorCode
	return o
}

// SetXErrorCode sets the xErrorCode to the update project internal server error response
func (o *UpdateProjectInternalServerError) SetXErrorCode(xErrorCode string) {
	o.XErrorCode = xErrorCode
}

// WithPayload adds the payload to the update project internal server error response
func (o *UpdateProjectInternalServerError) WithPayload(payload *models.Error) *UpdateProjectInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update project internal server error response
func (o *UpdateProjectInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateProjectInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Error-Code

	xErrorCode := o.XErrorCode
	if xErrorCode != "" {
		rw.Header().Set("X-Error-Code", xErrorCode)
	}

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
