exclude:
    - /src/api/models/.*
    - /src/api/proto/.*
    - /src/api/restapi/.*
    - /src/incremental/config/.*
    - /src/incremental/database/.*
    - /src/incremental/proto/.*
    - /src/project/config/.*
    - /src/project/database/.*
    - /src/project/proto/.*
    - /src/semver/config/.*
    - /src/semver/database/.*
    - /src/semver/proto/.*

component_depth: 1

languages:
    - go
    - script
