// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/project/project.proto

/*
Package project is a generated protocol buffer package.

It is generated from these files:
	proto/project/project.proto

It has these top-level messages:
	ListRequest
	ListResponse
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
	ProjectItem
*/
package project

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListRequest struct {
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ListResponse struct {
	Status   uint32         `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Projects []*ProjectItem `protobuf:"bytes,2,rep,name=projects" json:"projects,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ListResponse) GetProjects() []*ProjectItem {
	if m != nil {
		return m.Projects
	}
	return nil
}

type CreateRequest struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateResponse struct {
	Status uint32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Uuid   string `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type ReadRequest struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type ReadResponse struct {
	Status  uint32       `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Project *ProjectItem `protobuf:"bytes,2,opt,name=project" json:"project,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReadResponse) GetProject() *ProjectItem {
	if m != nil {
		return m.Project
	}
	return nil
}

type UpdateRequest struct {
	Uuid        string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type UpdateResponse struct {
	Status uint32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateResponse) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type ProjectItem struct {
	Uuid        string `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
}

func (m *ProjectItem) Reset()                    { *m = ProjectItem{} }
func (m *ProjectItem) String() string            { return proto.CompactTextString(m) }
func (*ProjectItem) ProtoMessage()               {}
func (*ProjectItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ProjectItem) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ProjectItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProjectItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*ListRequest)(nil), "project.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "project.ListResponse")
	proto.RegisterType((*CreateRequest)(nil), "project.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "project.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "project.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "project.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "project.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "project.UpdateResponse")
	proto.RegisterType((*ProjectItem)(nil), "project.ProjectItem")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Project service

type ProjectClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error)
}

type projectClient struct {
	c           client.Client
	serviceName string
}

func NewProjectClient(serviceName string, c client.Client) ProjectClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "project"
	}
	return &projectClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *projectClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Project.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Project.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectClient) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Project.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectClient) List(ctx context.Context, in *ListRequest, opts ...client.CallOption) (*ListResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Project.List", in)
	out := new(ListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Project service

type ProjectHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	List(context.Context, *ListRequest, *ListResponse) error
}

func RegisterProjectHandler(s server.Server, hdlr ProjectHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Project{hdlr}, opts...))
}

type Project struct {
	ProjectHandler
}

func (h *Project) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.ProjectHandler.Create(ctx, in, out)
}

func (h *Project) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.ProjectHandler.Read(ctx, in, out)
}

func (h *Project) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.ProjectHandler.Update(ctx, in, out)
}

func (h *Project) List(ctx context.Context, in *ListRequest, out *ListResponse) error {
	return h.ProjectHandler.List(ctx, in, out)
}

func init() { proto.RegisterFile("proto/project/project.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x4f, 0x83, 0x30,
	0x14, 0xc7, 0xc7, 0x8f, 0x30, 0x7d, 0x8c, 0x1d, 0x1a, 0x9d, 0x64, 0x5e, 0xb0, 0x27, 0x4e, 0x68,
	0x66, 0x3c, 0xcd, 0x9b, 0xf1, 0x60, 0xe2, 0xc1, 0x90, 0xf8, 0xeb, 0x88, 0xa3, 0x07, 0x4c, 0x06,
	0x48, 0xcb, 0x1f, 0xee, 0x7f, 0x60, 0xd6, 0x96, 0xfa, 0x18, 0xe2, 0x4e, 0x6d, 0x1f, 0x8f, 0xef,
	0xf7, 0xcb, 0xa7, 0x3c, 0x38, 0xaf, 0x9b, 0x4a, 0x54, 0x97, 0x75, 0x53, 0x7d, 0xb2, 0x8d, 0xe8,
	0xd6, 0x44, 0x56, 0xc9, 0x54, 0x1f, 0x69, 0x00, 0xfe, 0x63, 0xc1, 0x45, 0xca, 0xbe, 0x5a, 0xc6,
	0x05, 0x7d, 0x83, 0x99, 0x3a, 0xf2, 0xba, 0x2a, 0x39, 0x23, 0x0b, 0xf0, 0xb8, 0xc8, 0x44, 0xcb,
	0x43, 0x2b, 0xb2, 0xe2, 0x20, 0xd5, 0x27, 0x72, 0x05, 0x47, 0x5a, 0x81, 0x87, 0x76, 0xe4, 0xc4,
	0xfe, 0xea, 0x24, 0xe9, 0x1c, 0x9e, 0xd4, 0xfa, 0x20, 0xd8, 0x36, 0x35, 0x5d, 0xf4, 0x1e, 0x82,
	0xbb, 0x86, 0x65, 0x82, 0x69, 0x2b, 0x42, 0xc0, 0x2d, 0xb3, 0x2d, 0x93, 0xc2, 0xc7, 0xa9, 0xdc,
	0x93, 0x08, 0xfc, 0x9c, 0xf1, 0x4d, 0x53, 0xd4, 0xa2, 0xa8, 0xca, 0xd0, 0x96, 0x8f, 0x70, 0x89,
	0xde, 0xc2, 0xbc, 0x93, 0x39, 0x10, 0x91, 0x80, 0xdb, 0xb6, 0x45, 0xae, 0x45, 0xe4, 0x9e, 0x5e,
	0x80, 0x9f, 0xb2, 0x2c, 0x47, 0x11, 0x64, 0x8b, 0x85, 0x5a, 0x5e, 0x60, 0xa6, 0x5a, 0x0e, 0xc8,
	0x27, 0xd0, 0x31, 0x94, 0x0e, 0x63, 0x00, 0x0c, 0xe8, 0x77, 0x08, 0x9e, 0xeb, 0xbc, 0xff, 0xfd,
	0xfb, 0xe6, 0x86, 0x89, 0x3d, 0xce, 0xc4, 0x19, 0x32, 0x89, 0x61, 0xde, 0x49, 0xff, 0x1f, 0x9a,
	0xbe, 0x82, 0x8f, 0xc2, 0xfd, 0x85, 0xc8, 0x44, 0x70, 0xc6, 0x23, 0xb8, 0x83, 0x08, 0xab, 0x6f,
	0x0b, 0xa6, 0x5a, 0x99, 0xac, 0xc1, 0x53, 0x57, 0x44, 0x16, 0x06, 0x49, 0xef, 0xea, 0x97, 0x67,
	0x83, 0xba, 0xca, 0x4d, 0x27, 0xe4, 0x06, 0xdc, 0x1d, 0x7e, 0xf2, 0x4b, 0x13, 0x5d, 0xd8, 0xf2,
	0x74, 0xaf, 0x6a, 0x5e, 0x5b, 0x83, 0xa7, 0x10, 0x20, 0xcf, 0x1e, 0x6e, 0xe4, 0xd9, 0x67, 0xa5,
	0x3c, 0x77, 0x3f, 0x3d, 0xf2, 0x44, 0x23, 0x81, 0x3c, 0xf1, 0x64, 0xd0, 0xc9, 0x87, 0x27, 0x47,
	0xe9, 0xfa, 0x27, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xe8, 0x75, 0x1a, 0x69, 0x03, 0x00, 0x00,
}
