package version_semantic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"

	"github.com/go-openapi/runtime"

	"api/models"
)

/*SemverGenerateCreated Generate semantic version response

swagger:response semverGenerateCreated
*/
type SemverGenerateCreated struct {

	// In: body
	Payload *models.Semver `json:"body,omitempty"`
}

// NewSemverGenerateCreated creates SemverGenerateCreated with default headers values
func NewSemverGenerateCreated() *SemverGenerateCreated {
	return &SemverGenerateCreated{}
}

// WithPayload adds the payload to the semver generate created response
func (o *SemverGenerateCreated) WithPayload(payload *models.Semver) *SemverGenerateCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the semver generate created response
func (o *SemverGenerateCreated) SetPayload(payload *models.Semver) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SemverGenerateCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SemverGenerateInternalServerError Error response

swagger:response semverGenerateInternalServerError
*/
type SemverGenerateInternalServerError struct {
	/*
	  Required: true
	*/
	XErrorCode string `json:"X-Error-Code"`

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewSemverGenerateInternalServerError creates SemverGenerateInternalServerError with default headers values
func NewSemverGenerateInternalServerError() *SemverGenerateInternalServerError {
	return &SemverGenerateInternalServerError{}
}

// WithXErrorCode adds the xErrorCode to the semver generate internal server error response
func (o *SemverGenerateInternalServerError) WithXErrorCode(xErrorCode string) *SemverGenerateInternalServerError {
	o.XErrorCode = xErrorCode
	return o
}

// SetXErrorCode sets the xErrorCode to the semver generate internal server error response
func (o *SemverGenerateInternalServerError) SetXErrorCode(xErrorCode string) {
	o.XErrorCode = xErrorCode
}

// WithPayload adds the payload to the semver generate internal server error response
func (o *SemverGenerateInternalServerError) WithPayload(payload *models.Error) *SemverGenerateInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the semver generate internal server error response
func (o *SemverGenerateInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SemverGenerateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Error-Code
	rw.Header().Add("X-Error-Code", fmt.Sprintf("%v", o.XErrorCode))

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
