version: "2"

services:
## semver
    service.semver:
        build: ../../go #base path is "devops/docker/compose/env"
        working_dir: /go/src/semver
        command: sh -c "consul agent -node=agent-semver -data-dir /tmp/consul"
        depends_on:
            - service.semver.db
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - APP_HTTP_PORT=${APP_HTTP_PORT}
            - APP_DATABASE_HOST=service.semver.db
        volumes:
           - ../../../../src/semver:/go/src/semver #base path is "devops/docker/compose/env"

    service.semver.db:
        image: 'postgres:9.5'
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - service.semver.dbdata:/var/lib/postgresql

volumes:
    service.semver.dbdata:
        driver: local
