// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "api/models"
)

// ReadProjectReader is a Reader for the ReadProject structure.
type ReadProjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadProjectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewReadProjectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewReadProjectNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewReadProjectInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewReadProjectOK creates a ReadProjectOK with default headers values
func NewReadProjectOK() *ReadProjectOK {
	return &ReadProjectOK{}
}

/*ReadProjectOK handles this case with default header values.

Project response
*/
type ReadProjectOK struct {
	XErrorCode string

	Payload *models.Project
}

func (o *ReadProjectOK) Error() string {
	return fmt.Sprintf("[GET /projects/{uuid}][%d] readProjectOK  %+v", 200, o.Payload)
}

func (o *ReadProjectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header X-Error-Code
	o.XErrorCode = response.GetHeader("X-Error-Code")

	o.Payload = new(models.Project)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReadProjectNotFound creates a ReadProjectNotFound with default headers values
func NewReadProjectNotFound() *ReadProjectNotFound {
	return &ReadProjectNotFound{}
}

/*ReadProjectNotFound handles this case with default header values.

Project response
*/
type ReadProjectNotFound struct {
	XErrorCode string

	Payload *models.Project
}

func (o *ReadProjectNotFound) Error() string {
	return fmt.Sprintf("[GET /projects/{uuid}][%d] readProjectNotFound  %+v", 404, o.Payload)
}

func (o *ReadProjectNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header X-Error-Code
	o.XErrorCode = response.GetHeader("X-Error-Code")

	o.Payload = new(models.Project)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReadProjectInternalServerError creates a ReadProjectInternalServerError with default headers values
func NewReadProjectInternalServerError() *ReadProjectInternalServerError {
	return &ReadProjectInternalServerError{}
}

/*ReadProjectInternalServerError handles this case with default header values.

Error response
*/
type ReadProjectInternalServerError struct {
	XErrorCode string

	Payload *models.Error
}

func (o *ReadProjectInternalServerError) Error() string {
	return fmt.Sprintf("[GET /projects/{uuid}][%d] readProjectInternalServerError  %+v", 500, o.Payload)
}

func (o *ReadProjectInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header X-Error-Code
	o.XErrorCode = response.GetHeader("X-Error-Code")

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
