// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReadProjectParams creates a new ReadProjectParams object
// with the default values initialized.
func NewReadProjectParams() *ReadProjectParams {
	var ()
	return &ReadProjectParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReadProjectParamsWithTimeout creates a new ReadProjectParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReadProjectParamsWithTimeout(timeout time.Duration) *ReadProjectParams {
	var ()
	return &ReadProjectParams{

		timeout: timeout,
	}
}

// NewReadProjectParamsWithContext creates a new ReadProjectParams object
// with the default values initialized, and the ability to set a context for a request
func NewReadProjectParamsWithContext(ctx context.Context) *ReadProjectParams {
	var ()
	return &ReadProjectParams{

		Context: ctx,
	}
}

// NewReadProjectParamsWithHTTPClient creates a new ReadProjectParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReadProjectParamsWithHTTPClient(client *http.Client) *ReadProjectParams {
	var ()
	return &ReadProjectParams{
		HTTPClient: client,
	}
}

/*ReadProjectParams contains all the parameters to send to the API endpoint
for the read project operation typically these are written to a http.Request
*/
type ReadProjectParams struct {

	/*UUID
	  Project ID in UUID format

	*/
	UUID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the read project params
func (o *ReadProjectParams) WithTimeout(timeout time.Duration) *ReadProjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the read project params
func (o *ReadProjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the read project params
func (o *ReadProjectParams) WithContext(ctx context.Context) *ReadProjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the read project params
func (o *ReadProjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the read project params
func (o *ReadProjectParams) WithHTTPClient(client *http.Client) *ReadProjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the read project params
func (o *ReadProjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUUID adds the uuid to the read project params
func (o *ReadProjectParams) WithUUID(uuid strfmt.UUID) *ReadProjectParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the read project params
func (o *ReadProjectParams) SetUUID(uuid strfmt.UUID) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *ReadProjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
