swagger: '2.0'
info:
    title: Release Manager
    description: This application generate version for your software.
    contact:
        name: Vital Leshchyk
        url: https://github.com/itcreator/release-manager
        email: vitalleshchyk@gmail.com
    license:
        name: 3-Clause BSD
        url: https://github.com/itcreator/release-manager-micro/blob/master/LICENSE
    version: 0.2.0

schemes:
    - http
#    - https

consumes:
    - application/release-manager.v1+json
produces:
    - application/release-manager.v1+json
tags:
    - name: project
      description: manages project
    - name: versionSemantic
      description: Generate version tag. See also http://semver.org/spec/v2.0.0.html

paths:
    /projects:
        get:
            operationId: listProjects
            tags:
                - project
            summary: List the projects
            description: |
                Get all projects list.

            responses:
                200:
                    description: Successful response
                    schema:
                        title: ProjectList
                        type: array
                        items:
                            $ref: "#/definitions/Project"
                500:
                    $ref: "#/responses/ErrorResponse"
        post:
            operationId: createProject
            tags:
                - project
            summary: Create new projects
            parameters:
                - name: body
                  in: body
                  schema:
                      $ref: "#/definitions/Project"
            responses:
                201:
                    $ref: "#/responses/ProjectResponse"
                500:
                    $ref: "#/responses/ErrorResponse"

    /projects/{projectId}/version/semantic:
        parameters:
          - type: integer
            format: uint64
            name: projectId
            in: path
            required: true
        post:
            operationId: semverGenerate
            tags:
                - versionSemantic
            summary: Generate new semantic version number (based on gitflow)
            description: |
                Semantic Versioning 2.0.0
                See also http://semver.org/spec/v2.0.0.html
                Based on branching model [GitFlow](http://nvie.com/posts/a-successful-git-branching-model/)

            parameters:
                - name: body
                  in: body
                  schema:
                      $ref: "#/definitions/SemverGenerateParams"
            responses:
                201:
                    $ref: "#/responses/SemverGenerateResponse"
                500:
                    $ref: "#/responses/ErrorResponse"

    /projects/{id}:
        parameters:
            - type: integer
              format: uint64
              name: id
              in: path
              required: true
        get:
            operationId: readProject
            tags:
                - project
            summary: Read the projects
            description: |
                Get all projects list
            responses:
                200:
                    $ref: "#/responses/ProjectResponse"
                404:
                    $ref: "#/responses/ProjectResponse"
                500:
                    $ref: "#/responses/ErrorResponse"
        put:
            tags:
                - project
            operationId: updateProject
            parameters:
                - name: body
                  in: body
                  schema:
                      $ref: "#/definitions/Project"
            responses:
                200:
                    $ref: "#/responses/ProjectResponse"
                404:
                    $ref: "#/responses/ProjectResponse"
                500:
                    $ref: "#/responses/ErrorResponse"

    /increamental_version/{projectName}:
        parameters:
          - type: string
            name: projectName
            maxLength: 100
            x-nullable: false #don't generate reference
            in: path
            required: true
        post:
            operationId: incrementalGenerate
            tags:
                - versionIncremental
            summary: Generate new incremental version number
            description: |
                Incremental Versioning

            responses:
                201:
                    $ref: "#/responses/IncrementalGenerateResponse"
                500:
                    $ref: "#/responses/ErrorResponse"
        put:
            operationId: incrementalUpdate
            tags:
                - versionIncremental
            summary: Update incremental version number (Only for maintenance)
            description: |
                Incremental Versioning
                Update revision number

            parameters:
              - name: body
                in: body
                schema:
                    $ref: "#/definitions/IncrementalVersionNumber"
            responses:
                200:
                    $ref: "#/responses/IncrementalUpdateResponse"
                500:
                    $ref: "#/responses/ErrorResponse"

        delete:
            operationId: incrementalDelete
            tags:
                - versionIncremental
            summary: Delete incremental version number (RESET)
            description: |
                Delete generated version

            responses:
                204:
                    description: The resource was deleted successfully.
                500:
                    $ref: "#/responses/ErrorResponse"

responses:
    ErrorResponse:
        description: Error response
        headers:
            X-Error-Code:
                type: string
        schema:
            $ref: "#/definitions/Error"
    ProjectResponse:
        description: Project response
        headers:
            X-Error-Code:
                type: string
        schema:
            $ref: "#/definitions/Project"

    SemverGenerateResponse:
        description: Generate semantic version response
        schema:
            $ref: "#/definitions/SemverNumber"

    IncrementalGenerateResponse:
        description: Generate incremental version response
        schema:
            $ref: "#/definitions/IncrementalVersionNumber"

    IncrementalUpdateResponse:
        description: Update incremental version response
        schema:
            $ref: "#/definitions/IncrementalVersionNumber"


definitions:
    Error:
        title: Error Structure
        description: |
            Contains all the properties any error response from the API will contain.
            Some properties are optional so might be empty most of the time
        type: object
        required:
            - code
            - message
        properties:
            code:
                description: the error code, this is not necessarily the http status code
                type: integer
                format: int32
            message:
                description: a human readable version of the error
                type: string
            helpUrl:
                description: an optional url for getting more help about this error
                type: string
                format: uri

    Project:
        title: Project
        type: object
        required:
            - name
        properties:
            id:
                title: The id of the project.
                description: A unique identifier for the project. These are created in ascending order.
                type: integer
                format: uint64
                readOnly: true
            name:
                title: The name of the project.
                type: string
                minLength: 2
                maxLength: 150
                x-nullable: false #don't generate reference
            description:
                title: The description of the project.
                type: string
                maxLength: 4000
                x-nullable: false #don't generate reference

    SemverGenerateParams:
        title: Paremeters for generate version number for project (Semantic Versioning)
        type: object
        required:
            - major
            - minor
            - branch
        properties:
            major:
                title: Major number
                description: MAJOR version when you make incompatible API changes
                type: integer
                format: uint32
                readOnly: true
            minor:
                title: Minor number
                description: MINOR version when you add functionality in a backwards-compatible manner
                type: integer
                format: uint32
                readOnly: true
            branch:
                title: Name of branch for which needed to generate a version tag.
                type: string
                minLength: 2
                maxLength: 150
                x-nullable: false #don't generate reference

    SemverNumber:
        title: Semver Number
        type: object
        required:
            - version
        properties:
            version:
                title: The version number
                type: string
                minLength: 3
                maxLength: 150
                x-nullable: false #don't generate reference

    IncrementalVersionNumber:
        title: Incremental Version Number
        type: object
        required:
            - version
        properties:
            version:
                title: The version number
                type: integer
                format: uint64
                x-nullable: false #don't generate reference
