// Code generated by go-swagger; DO NOT EDIT.

package version_semantic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "api/models"
)

// NewSemverGenerateParams creates a new SemverGenerateParams object
// with the default values initialized.
func NewSemverGenerateParams() *SemverGenerateParams {
	var ()
	return &SemverGenerateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSemverGenerateParamsWithTimeout creates a new SemverGenerateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSemverGenerateParamsWithTimeout(timeout time.Duration) *SemverGenerateParams {
	var ()
	return &SemverGenerateParams{

		timeout: timeout,
	}
}

// NewSemverGenerateParamsWithContext creates a new SemverGenerateParams object
// with the default values initialized, and the ability to set a context for a request
func NewSemverGenerateParamsWithContext(ctx context.Context) *SemverGenerateParams {
	var ()
	return &SemverGenerateParams{

		Context: ctx,
	}
}

// NewSemverGenerateParamsWithHTTPClient creates a new SemverGenerateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSemverGenerateParamsWithHTTPClient(client *http.Client) *SemverGenerateParams {
	var ()
	return &SemverGenerateParams{
		HTTPClient: client,
	}
}

/*SemverGenerateParams contains all the parameters to send to the API endpoint
for the semver generate operation typically these are written to a http.Request
*/
type SemverGenerateParams struct {

	/*Body*/
	Body *models.SemverGenerateParams
	/*ProjectUUID
	  Project ID in UUID format

	*/
	ProjectUUID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the semver generate params
func (o *SemverGenerateParams) WithTimeout(timeout time.Duration) *SemverGenerateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the semver generate params
func (o *SemverGenerateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the semver generate params
func (o *SemverGenerateParams) WithContext(ctx context.Context) *SemverGenerateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the semver generate params
func (o *SemverGenerateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the semver generate params
func (o *SemverGenerateParams) WithHTTPClient(client *http.Client) *SemverGenerateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the semver generate params
func (o *SemverGenerateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the semver generate params
func (o *SemverGenerateParams) WithBody(body *models.SemverGenerateParams) *SemverGenerateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the semver generate params
func (o *SemverGenerateParams) SetBody(body *models.SemverGenerateParams) {
	o.Body = body
}

// WithProjectUUID adds the projectUUID to the semver generate params
func (o *SemverGenerateParams) WithProjectUUID(projectUUID strfmt.UUID) *SemverGenerateParams {
	o.SetProjectUUID(projectUUID)
	return o
}

// SetProjectUUID adds the projectUuid to the semver generate params
func (o *SemverGenerateParams) SetProjectUUID(projectUUID strfmt.UUID) {
	o.ProjectUUID = projectUUID
}

// WriteToRequest writes these params to a swagger request
func (o *SemverGenerateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param projectUuid
	if err := r.SetPathParam("projectUuid", o.ProjectUUID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
