// Code generated by go-swagger; DO NOT EDIT.

package version_semantic

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new version semantic API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for version semantic API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
SemverGenerate generates new semantic version number based on gitflow

Semantic Versioning 2.0.0
See also http://semver.org/spec/v2.0.0.html
Based on branching model [GitFlow](http://nvie.com/posts/a-successful-git-branching-model/)

*/
func (a *Client) SemverGenerate(params *SemverGenerateParams) (*SemverGenerateCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewSemverGenerateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "semverGenerate",
		Method:             "POST",
		PathPattern:        "/projects/{projectUuid}/version/semantic",
		ProducesMediaTypes: []string{"application/release-manager.v1+json"},
		ConsumesMediaTypes: []string{"application/release-manager.v1+json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &SemverGenerateReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*SemverGenerateCreated), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
