version: "3"

services:
## version incremental
    service.version.incremental:
        #base path is "ops/docker/compose/env"
#        build: ../../../../../go-micro-stack/go #Dockerfile debug
        image: itcreator/go-micro-stack
        working_dir: /go/src/incremental
        command: sh -c "consul agent -node=agent-version-incremental -data-dir /tmp/consul"
        depends_on:
            - service.version.incremental.db
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - APP_HTTP_PORT=${APP_HTTP_PORT}
            - APP_DATABASE_HOST=service.version.incremental.db
        volumes:
           - ../../../../src/incremental:/go/src/incremental:Z #base path is "ops/docker/compose/env"

    service.version.incremental.db:
        image: 'postgres:9.6'
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - service.version.incremental.dbdata:/var/lib/postgresql

volumes:
    service.version.incremental.dbdata:
          driver: local
