version: "3"

services:
## semver
    service.semver:
        #base path is "ops/docker/compose/env"
#        build: ../../../../../go-micro-stack/go #Dockerfile debug
        image: itcreator/go-micro-stack:0.4
        working_dir: /go/src/semver
        command: sh -c "consul agent -node=agent-semver -data-dir /tmp/consul"
        depends_on:
            - service.semver.db
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - APP_HTTP_PORT=${APP_HTTP_PORT}
            - APP_DATABASE_HOST=service.semver.db
        volumes:
           - ../../../../src/semver:/go/src/semver:Z #base path is "ops/docker/compose/env"

    service.semver.db:
        image: 'postgres:12.1'
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - ../../../../var/db/semver/data:/var/lib/postgresql/data
