// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IncrementalVersionNumber Incremental Version Number
// swagger:model IncrementalVersionNumber
type IncrementalVersionNumber struct {

	// The version number
	// Required: true
	Version uint64 `json:"version"`
}

// Validate validates this incremental version number
func (m *IncrementalVersionNumber) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVersion(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IncrementalVersionNumber) validateVersion(formats strfmt.Registry) error {

	if err := validate.Required("version", "body", uint64(m.Version)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IncrementalVersionNumber) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IncrementalVersionNumber) UnmarshalBinary(b []byte) error {
	var res IncrementalVersionNumber
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
