package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

/*SemverNumber Semver Number

swagger:model SemverNumber
*/
type SemverNumber struct {

	/* The id of the generated version number.

	A unique identifier for the generated version number.

	Read Only: true
	*/
	ID uint64 `json:"id,omitempty"`

	/* The version number

	Required: true
	Max Length: 150
	Min Length: 3
	*/
	Version string `json:"version"`
}

// Validate validates this semver number
func (m *SemverNumber) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVersion(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SemverNumber) validateVersion(formats strfmt.Registry) error {

	if err := validate.RequiredString("version", "body", string(m.Version)); err != nil {
		return err
	}

	if err := validate.MinLength("version", "body", string(m.Version), 3); err != nil {
		return err
	}

	if err := validate.MaxLength("version", "body", string(m.Version), 150); err != nil {
		return err
	}

	return nil
}
