// Code generated by go-swagger; DO NOT EDIT.

package version_incremental

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewIncrementalGenerateParams creates a new IncrementalGenerateParams object
// no default values defined in spec.
func NewIncrementalGenerateParams() IncrementalGenerateParams {

	return IncrementalGenerateParams{}
}

// IncrementalGenerateParams contains all the bound params for the incremental generate operation
// typically these are obtained from a http.Request
//
// swagger:parameters incrementalGenerate
type IncrementalGenerateParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  Max Length: 100
	  In: path
	*/
	ProjectName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewIncrementalGenerateParams() beforehand.
func (o *IncrementalGenerateParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rProjectName, rhkProjectName, _ := route.Params.GetOK("projectName")
	if err := o.bindProjectName(rProjectName, rhkProjectName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *IncrementalGenerateParams) bindProjectName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ProjectName = raw

	if err := o.validateProjectName(formats); err != nil {
		return err
	}

	return nil
}

func (o *IncrementalGenerateParams) validateProjectName(formats strfmt.Registry) error {

	if err := validate.MaxLength("projectName", "path", o.ProjectName, 100); err != nil {
		return err
	}

	return nil
}
