package version_incremental

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"

	"github.com/go-openapi/runtime"

	"api/models"
)

/*IncrementalDeleteNoContent incremental delete no content

swagger:response incrementalDeleteNoContent
*/
type IncrementalDeleteNoContent struct {
}

// NewIncrementalDeleteNoContent creates IncrementalDeleteNoContent with default headers values
func NewIncrementalDeleteNoContent() *IncrementalDeleteNoContent {
	return &IncrementalDeleteNoContent{}
}

// WriteResponse to the client
func (o *IncrementalDeleteNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
}

/*IncrementalDeleteInternalServerError Error response

swagger:response incrementalDeleteInternalServerError
*/
type IncrementalDeleteInternalServerError struct {
	/*
	  Required: true
	*/
	XErrorCode string `json:"X-Error-Code"`

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewIncrementalDeleteInternalServerError creates IncrementalDeleteInternalServerError with default headers values
func NewIncrementalDeleteInternalServerError() *IncrementalDeleteInternalServerError {
	return &IncrementalDeleteInternalServerError{}
}

// WithXErrorCode adds the xErrorCode to the incremental delete internal server error response
func (o *IncrementalDeleteInternalServerError) WithXErrorCode(xErrorCode string) *IncrementalDeleteInternalServerError {
	o.XErrorCode = xErrorCode
	return o
}

// SetXErrorCode sets the xErrorCode to the incremental delete internal server error response
func (o *IncrementalDeleteInternalServerError) SetXErrorCode(xErrorCode string) {
	o.XErrorCode = xErrorCode
}

// WithPayload adds the payload to the incremental delete internal server error response
func (o *IncrementalDeleteInternalServerError) WithPayload(payload *models.Error) *IncrementalDeleteInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the incremental delete internal server error response
func (o *IncrementalDeleteInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IncrementalDeleteInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Error-Code
	rw.Header().Add("X-Error-Code", fmt.Sprintf("%v", o.XErrorCode))

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
