package version_incremental

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"

	"github.com/go-openapi/runtime"

	"api/models"
)

/*IncrementalGenerateCreated Generate incremental version response

swagger:response incrementalGenerateCreated
*/
type IncrementalGenerateCreated struct {

	// In: body
	Payload *models.IncrementalVersionNumber `json:"body,omitempty"`
}

// NewIncrementalGenerateCreated creates IncrementalGenerateCreated with default headers values
func NewIncrementalGenerateCreated() *IncrementalGenerateCreated {
	return &IncrementalGenerateCreated{}
}

// WithPayload adds the payload to the incremental generate created response
func (o *IncrementalGenerateCreated) WithPayload(payload *models.IncrementalVersionNumber) *IncrementalGenerateCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the incremental generate created response
func (o *IncrementalGenerateCreated) SetPayload(payload *models.IncrementalVersionNumber) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IncrementalGenerateCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*IncrementalGenerateInternalServerError Error response

swagger:response incrementalGenerateInternalServerError
*/
type IncrementalGenerateInternalServerError struct {
	/*
	  Required: true
	*/
	XErrorCode string `json:"X-Error-Code"`

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewIncrementalGenerateInternalServerError creates IncrementalGenerateInternalServerError with default headers values
func NewIncrementalGenerateInternalServerError() *IncrementalGenerateInternalServerError {
	return &IncrementalGenerateInternalServerError{}
}

// WithXErrorCode adds the xErrorCode to the incremental generate internal server error response
func (o *IncrementalGenerateInternalServerError) WithXErrorCode(xErrorCode string) *IncrementalGenerateInternalServerError {
	o.XErrorCode = xErrorCode
	return o
}

// SetXErrorCode sets the xErrorCode to the incremental generate internal server error response
func (o *IncrementalGenerateInternalServerError) SetXErrorCode(xErrorCode string) {
	o.XErrorCode = xErrorCode
}

// WithPayload adds the payload to the incremental generate internal server error response
func (o *IncrementalGenerateInternalServerError) WithPayload(payload *models.Error) *IncrementalGenerateInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the incremental generate internal server error response
func (o *IncrementalGenerateInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IncrementalGenerateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header X-Error-Code
	rw.Header().Add("X-Error-Code", fmt.Sprintf("%v", o.XErrorCode))

	rw.WriteHeader(500)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
