version: "3"

services:
#### Service Discovery
    consul:
#        build: ../../../../../go-micro-stack/consul #Dockerfile debug
        image: itcreator/go-micro-stack-consul:0.4
        depends_on:
            - service.api
        environment:
            - CONSUL_AGENTS
        expose:
          - "8500"
        ports:
          - "8500:8500"


#### API layer
    service.api:
        #base path is "ops/docker/compose/env"
#        build: ../../../../../go-micro-stack/go #Dockerfile debug
        image: itcreator/go-micro-stack:0.4
        working_dir: /go/src/api
        command: sh -c "consul agent -node=agent-api -data-dir /tmp/consul"

        volumes:
           - ../../../../src/api:/go/src/api:Z
        expose:
           - "80"
