version: "3"

services:
#### Service Discovery
    consul:
        image: itcreator/go-micro-stack-consul
        depends_on:
            - service.api
        environment:
            - CONSUL_AGENTS
        expose:
          - "8500"
        ports:
          - "8500:8500"


#### API layer
    service.api:
        #base path is "ops/docker/compose/env"
        image: itcreator/go-micro-stack
        working_dir: /go/src/api
        command: sh -c "consul agent -node=agent-api -data-dir /tmp/consul"

        volumes:
           - ../../../../src/api:/go/src/api:Z
           - ../../../../apiDoc:/apiDoc:Z
        expose:
           - "80"
