// Code generated by go-swagger; DO NOT EDIT.

package version_incremental

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "api/models"
)

// IncrementalDeleteReader is a Reader for the IncrementalDelete structure.
type IncrementalDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IncrementalDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewIncrementalDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewIncrementalDeleteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIncrementalDeleteNoContent creates a IncrementalDeleteNoContent with default headers values
func NewIncrementalDeleteNoContent() *IncrementalDeleteNoContent {
	return &IncrementalDeleteNoContent{}
}

/*IncrementalDeleteNoContent handles this case with default header values.

The resource was deleted successfully.
*/
type IncrementalDeleteNoContent struct {
}

func (o *IncrementalDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /increamental_version/{projectName}][%d] incrementalDeleteNoContent ", 204)
}

func (o *IncrementalDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewIncrementalDeleteInternalServerError creates a IncrementalDeleteInternalServerError with default headers values
func NewIncrementalDeleteInternalServerError() *IncrementalDeleteInternalServerError {
	return &IncrementalDeleteInternalServerError{}
}

/*IncrementalDeleteInternalServerError handles this case with default header values.

Error response
*/
type IncrementalDeleteInternalServerError struct {
	XErrorCode string

	Payload *models.Error
}

func (o *IncrementalDeleteInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /increamental_version/{projectName}][%d] incrementalDeleteInternalServerError  %+v", 500, o.Payload)
}

func (o *IncrementalDeleteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header X-Error-Code
	o.XErrorCode = response.GetHeader("X-Error-Code")

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
