// Code generated by go-swagger; DO NOT EDIT.

package version_incremental

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "api/models"
)

// IncrementalGenerateReader is a Reader for the IncrementalGenerate structure.
type IncrementalGenerateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IncrementalGenerateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewIncrementalGenerateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 500:
		result := NewIncrementalGenerateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIncrementalGenerateCreated creates a IncrementalGenerateCreated with default headers values
func NewIncrementalGenerateCreated() *IncrementalGenerateCreated {
	return &IncrementalGenerateCreated{}
}

/*IncrementalGenerateCreated handles this case with default header values.

Generate incremental version response
*/
type IncrementalGenerateCreated struct {
	Payload *models.IncrementalVersionNumber
}

func (o *IncrementalGenerateCreated) Error() string {
	return fmt.Sprintf("[POST /increamental_version/{projectName}][%d] incrementalGenerateCreated  %+v", 201, o.Payload)
}

func (o *IncrementalGenerateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IncrementalVersionNumber)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIncrementalGenerateInternalServerError creates a IncrementalGenerateInternalServerError with default headers values
func NewIncrementalGenerateInternalServerError() *IncrementalGenerateInternalServerError {
	return &IncrementalGenerateInternalServerError{}
}

/*IncrementalGenerateInternalServerError handles this case with default header values.

Error response
*/
type IncrementalGenerateInternalServerError struct {
	XErrorCode string

	Payload *models.Error
}

func (o *IncrementalGenerateInternalServerError) Error() string {
	return fmt.Sprintf("[POST /increamental_version/{projectName}][%d] incrementalGenerateInternalServerError  %+v", 500, o.Payload)
}

func (o *IncrementalGenerateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header X-Error-Code
	o.XErrorCode = response.GetHeader("X-Error-Code")

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
