// Code generated by go-swagger; DO NOT EDIT.

package version_incremental

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewIncrementalGenerateParams creates a new IncrementalGenerateParams object
// with the default values initialized.
func NewIncrementalGenerateParams() *IncrementalGenerateParams {
	var ()
	return &IncrementalGenerateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIncrementalGenerateParamsWithTimeout creates a new IncrementalGenerateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIncrementalGenerateParamsWithTimeout(timeout time.Duration) *IncrementalGenerateParams {
	var ()
	return &IncrementalGenerateParams{

		timeout: timeout,
	}
}

// NewIncrementalGenerateParamsWithContext creates a new IncrementalGenerateParams object
// with the default values initialized, and the ability to set a context for a request
func NewIncrementalGenerateParamsWithContext(ctx context.Context) *IncrementalGenerateParams {
	var ()
	return &IncrementalGenerateParams{

		Context: ctx,
	}
}

// NewIncrementalGenerateParamsWithHTTPClient creates a new IncrementalGenerateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIncrementalGenerateParamsWithHTTPClient(client *http.Client) *IncrementalGenerateParams {
	var ()
	return &IncrementalGenerateParams{
		HTTPClient: client,
	}
}

/*IncrementalGenerateParams contains all the parameters to send to the API endpoint
for the incremental generate operation typically these are written to a http.Request
*/
type IncrementalGenerateParams struct {

	/*ProjectName*/
	ProjectName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the incremental generate params
func (o *IncrementalGenerateParams) WithTimeout(timeout time.Duration) *IncrementalGenerateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the incremental generate params
func (o *IncrementalGenerateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the incremental generate params
func (o *IncrementalGenerateParams) WithContext(ctx context.Context) *IncrementalGenerateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the incremental generate params
func (o *IncrementalGenerateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the incremental generate params
func (o *IncrementalGenerateParams) WithHTTPClient(client *http.Client) *IncrementalGenerateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the incremental generate params
func (o *IncrementalGenerateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectName adds the projectName to the incremental generate params
func (o *IncrementalGenerateParams) WithProjectName(projectName string) *IncrementalGenerateParams {
	o.SetProjectName(projectName)
	return o
}

// SetProjectName adds the projectName to the incremental generate params
func (o *IncrementalGenerateParams) SetProjectName(projectName string) {
	o.ProjectName = projectName
}

// WriteToRequest writes these params to a swagger request
func (o *IncrementalGenerateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param projectName
	if err := r.SetPathParam("projectName", o.ProjectName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
