// Code generated by go-swagger; DO NOT EDIT.

package version_incremental

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "api/models"
)

// NewIncrementalUpdateParams creates a new IncrementalUpdateParams object
// with the default values initialized.
func NewIncrementalUpdateParams() *IncrementalUpdateParams {
	var ()
	return &IncrementalUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIncrementalUpdateParamsWithTimeout creates a new IncrementalUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIncrementalUpdateParamsWithTimeout(timeout time.Duration) *IncrementalUpdateParams {
	var ()
	return &IncrementalUpdateParams{

		timeout: timeout,
	}
}

// NewIncrementalUpdateParamsWithContext creates a new IncrementalUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewIncrementalUpdateParamsWithContext(ctx context.Context) *IncrementalUpdateParams {
	var ()
	return &IncrementalUpdateParams{

		Context: ctx,
	}
}

// NewIncrementalUpdateParamsWithHTTPClient creates a new IncrementalUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIncrementalUpdateParamsWithHTTPClient(client *http.Client) *IncrementalUpdateParams {
	var ()
	return &IncrementalUpdateParams{
		HTTPClient: client,
	}
}

/*IncrementalUpdateParams contains all the parameters to send to the API endpoint
for the incremental update operation typically these are written to a http.Request
*/
type IncrementalUpdateParams struct {

	/*Body*/
	Body *models.IncrementalVersionNumber
	/*ProjectName*/
	ProjectName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the incremental update params
func (o *IncrementalUpdateParams) WithTimeout(timeout time.Duration) *IncrementalUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the incremental update params
func (o *IncrementalUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the incremental update params
func (o *IncrementalUpdateParams) WithContext(ctx context.Context) *IncrementalUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the incremental update params
func (o *IncrementalUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the incremental update params
func (o *IncrementalUpdateParams) WithHTTPClient(client *http.Client) *IncrementalUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the incremental update params
func (o *IncrementalUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the incremental update params
func (o *IncrementalUpdateParams) WithBody(body *models.IncrementalVersionNumber) *IncrementalUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the incremental update params
func (o *IncrementalUpdateParams) SetBody(body *models.IncrementalVersionNumber) {
	o.Body = body
}

// WithProjectName adds the projectName to the incremental update params
func (o *IncrementalUpdateParams) WithProjectName(projectName string) *IncrementalUpdateParams {
	o.SetProjectName(projectName)
	return o
}

// SetProjectName adds the projectName to the incremental update params
func (o *IncrementalUpdateParams) SetProjectName(projectName string) {
	o.ProjectName = projectName
}

// WriteToRequest writes these params to a swagger request
func (o *IncrementalUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param projectName
	if err := r.SetPathParam("projectName", o.ProjectName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
